export const enum Action {
  GET_STORIES = 'GET_STORIES',
  GET_STORIES_SUCCEEDED = 'GET_STORIES_SUCCEEDED',
  GET_STORIES_FAILED = 'GET_STORIES_FAILED',
  GET_STORY = 'GET_STORY',
  GET_STORY_SUCCEEDED = 'GET_STORY_SUCCEEDED',
  GET_STORY_FAILED = 'GET_STORY_FAILED',
}
